name: Deploy Astro site to Neocities

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Install dependencies
      - name: Install dependencies
        run: npm ci

      # Build Astro site
      - name: Build site
        run: npm run build

      # Deploy ONLY the dist folder
      - name: Deploy to Neocities
        uses: bcomnes/deploy-to-neocities@v3.0.4
        with:
          api_key: ${{ secrets.NEOCITIES_API_TOKEN }}
        # Tell the action to only upload dist/
        env:
          NEOCITIES_PATH: dist
